[package]
name = "axum-wist"
version = "0.0.0"
edition = "2024"
license = "CC0-1.0"
description = "Wist integration for Axum"

[dependencies]
axum = { version = "0.8.3", default-features = false, features = ["http1"] }
bytes = "1.10.1"
rand = "0.9.0"
wist = "0.1.4"
